from enum import StrEnum


class RoleName(StrEnum):
    ADMIN = "ADMIN"
    ATENDIMENTO = "ATENDIMENTO"
    MECANICO = "MECANICO"
    ESTOQUE = "ESTOQUE"
    VENDEDOR = "VENDEDOR"
    FINANCEIRO = "FINANCEIRO"
    GERENCIA = "GERENCIA"


class AttendanceType(StrEnum):
    SERVICO_DIRETO = "SERVICO_DIRETO"
    ORCAMENTO = "ORCAMENTO"


class MachineEntryStatus(StrEnum):
    RECEBIDA = "RECEBIDA"
    OS_CRIADA = "OS_CRIADA"
    ENTREGUE = "ENTREGUE"
    CANCELADA = "CANCELADA"


class WorkOrderStatus(StrEnum):
    RECEBIDA = "RECEBIDA"
    AGUARDANDO_DIAGNOSTICO = "AGUARDANDO_DIAGNOSTICO"
    EM_DIAGNOSTICO = "EM_DIAGNOSTICO"
    AGUARDANDO_ORCAMENTO = "AGUARDANDO_ORCAMENTO"
    AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO"
    APROVADA = "APROVADA"
    RECUSADA = "RECUSADA"
    AGUARDANDO_PECA = "AGUARDANDO_PECA"
    EM_MANUTENCAO = "EM_MANUTENCAO"
    FINALIZADA = "FINALIZADA"
    PRONTA_PARA_ENTREGA = "PRONTA_PARA_ENTREGA"
    ENTREGUE = "ENTREGUE"
    CANCELADA = "CANCELADA"


class BudgetStatus(StrEnum):
    RASCUNHO = "RASCUNHO"
    ENVIADO = "ENVIADO"
    AGUARDANDO_RESPOSTA = "AGUARDANDO_RESPOSTA"
    APROVADO = "APROVADO"
    APROVADO_PARCIALMENTE = "APROVADO_PARCIALMENTE"
    RECUSADO = "RECUSADO"
    EXPIRADO = "EXPIRADO"
    CANCELADO = "CANCELADO"


class BudgetItemType(StrEnum):
    PECA = "PECA"
    SERVICO = "SERVICO"


class StockMovementType(StrEnum):
    ENTRADA_COMPRA = "ENTRADA_COMPRA"
    VENDA_BALCAO = "VENDA_BALCAO"
    USO_EM_OS = "USO_EM_OS"
    DEVOLUCAO = "DEVOLUCAO"
    AJUSTE_POSITIVO = "AJUSTE_POSITIVO"
    AJUSTE_NEGATIVO = "AJUSTE_NEGATIVO"
    CANCELAMENTO_VENDA = "CANCELAMENTO_VENDA"
    ESTORNO_OS = "ESTORNO_OS"


class SaleStatus(StrEnum):
    ABERTA = "ABERTA"
    FINALIZADA = "FINALIZADA"
    CANCELADA = "CANCELADA"


class FiscalInvoiceStatus(StrEnum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    ISSUED = "ISSUED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"


class PaymentStatus(StrEnum):
    PENDENTE = "PENDENTE"
    PAGO = "PAGO"
    CANCELADO = "CANCELADO"


class PrintDocumentType(StrEnum):
    CUSTOMER_ENTRY_RECEIPT = "CUSTOMER_ENTRY_RECEIPT"
    MACHINE_TAG = "MACHINE_TAG"
    BUDGET = "BUDGET"
    WORK_ORDER = "WORK_ORDER"
    SALE_RECEIPT = "SALE_RECEIPT"


class PrintJobStatus(StrEnum):
    CREATED = "CREATED"
    PRINTED = "PRINTED"
    CANCELLED = "CANCELLED"
